/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package id.my.rizalanggoro.emasku.openapi.models

import id.my.rizalanggoro.emasku.openapi.models.DomainsGold

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param gold 
 */


data class CreateGoldRes (

    @SerializedName("gold")
    val gold: DomainsGold

) {


}

