/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package id.my.rizalanggoro.emasku.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param note 
 * @param price 
 * @param purchaseDate 
 * @param userId 
 * @param weight 
 */


data class DomainsGold (

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("note")
    val note: kotlin.String,

    @SerializedName("price")
    val price: java.math.BigDecimal,

    @SerializedName("purchase_date")
    val purchaseDate: kotlin.String,

    @SerializedName("user_id")
    val userId: kotlin.Int,

    @SerializedName("weight")
    val weight: java.math.BigDecimal

) {


}

