/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package id.my.rizalanggoro.emasku.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param dollarRate 
 * @param dollarUpdatedAt 
 * @param globalXauPrice 
 * @param globalXauUpdatedAt 
 * @param xauJewelryPriceGram 
 * @param xauPriceGram 
 * @param xauPriceOunce 
 */


data class GetMarketSummaryRes (

    @SerializedName("dollar_rate")
    val dollarRate: java.math.BigDecimal? = null,

    @SerializedName("dollar_updated_at")
    val dollarUpdatedAt: kotlin.String? = null,

    @SerializedName("global_xau_price")
    val globalXauPrice: java.math.BigDecimal? = null,

    @SerializedName("global_xau_updated_at")
    val globalXauUpdatedAt: kotlin.String? = null,

    @SerializedName("xau_jewelry_price_gram")
    val xauJewelryPriceGram: java.math.BigDecimal? = null,

    @SerializedName("xau_price_gram")
    val xauPriceGram: java.math.BigDecimal? = null,

    @SerializedName("xau_price_ounce")
    val xauPriceOunce: java.math.BigDecimal? = null

) {


}

