/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package id.my.rizalanggoro.emasku.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param totalBuyPrice 
 * @param totalProfit 
 * @param totalSellPrice 
 * @param totalWeight 
 */


data class GetSummaryRes (

    @SerializedName("total_buy_price")
    val totalBuyPrice: java.math.BigDecimal,

    @SerializedName("total_profit")
    val totalProfit: java.math.BigDecimal,

    @SerializedName("total_sell_price")
    val totalSellPrice: java.math.BigDecimal,

    @SerializedName("total_weight")
    val totalWeight: java.math.BigDecimal

) {


}

