/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package id.my.rizalanggoro.emasku.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param email 
 * @param name 
 * @param password 
 */


data class RegisterReq (

    @SerializedName("email")
    val email: kotlin.String,

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("password")
    val password: kotlin.String

) {


}

