/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package id.my.rizalanggoro.emasku.openapi.models

import id.my.rizalanggoro.emasku.openapi.models.DomainsGold

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param durationInDays 
 * @param gold 
 * @param profit 
 * @param sellPrice 
 */


data class ResponsesGetAllGoldsItem (

    @SerializedName("duration_in_days")
    val durationInDays: kotlin.Int,

    @SerializedName("gold")
    val gold: DomainsGold,

    @SerializedName("profit")
    val profit: java.math.BigDecimal,

    @SerializedName("sell_price")
    val sellPrice: java.math.BigDecimal

) {


}

