/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package id.my.rizalanggoro.emasku.openapi.apis

import id.my.rizalanggoro.emasku.openapi.models.CreateGoldReq
import id.my.rizalanggoro.emasku.openapi.models.CreateGoldRes
import id.my.rizalanggoro.emasku.openapi.models.DeleteGoldByIdRes
import id.my.rizalanggoro.emasku.openapi.models.GetAllGoldsRes
import id.my.rizalanggoro.emasku.openapi.models.GetGoldByIdRes

import id.my.rizalanggoro.emasku.openapi.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import java.text.DateFormat

    open class GoldApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    jsonBlock: GsonBuilder.() -> Unit = ApiClient.JSON_DEFAULT,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
        jsonBlock,
    ) {

        /**
        * POST /api/v1/golds
        * 
        * 
         * @param body body 
         * @return CreateGoldRes
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun createGold(body: CreateGoldReq): HttpResponse<CreateGoldRes> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/golds",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * DELETE /api/v1/golds/{gold_id}
        * 
        * 
         * @param goldId gold_id 
         * @return DeleteGoldByIdRes
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun deleteGoldById(goldId: kotlin.Int): HttpResponse<DeleteGoldByIdRes> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v1/golds/{gold_id}".replace("{" + "gold_id" + "}", "$goldId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /api/v1/golds
        * 
        * 
         * @return GetAllGoldsRes
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun getAllGolds(): HttpResponse<GetAllGoldsRes> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/golds",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /api/v1/golds/{gold_id}
        * 
        * 
         * @param goldId gold_id 
         * @return GetGoldByIdRes
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun getGoldById(goldId: kotlin.Int): HttpResponse<GetGoldByIdRes> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/golds/{gold_id}".replace("{" + "gold_id" + "}", "$goldId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
